### PR TITLE
Force close the http-client on IOAnalytics.close()

### PR DESCRIPTION
**Pull request by sigurdm**
This is part of the solution of: https://github.com/dart-lang/sdk/issues/45235

### CODE REVIEW

**Review by jonasfj — APPROVED** [review]
Seems fine... pending connections will also be cancelled by this (at-least when I tested on linux).

**Review by devoncarew — APPROVED** [review]
lgtm - thanks!

**Comment by devoncarew** [comment]
We can consume this from the sdk w/o a publish, but let me know if you do want a publish.

**Comment by sigurdm** [comment]
I'd say let's publish - I added a CHANGELOG entry and version bump.

**Review by devoncarew — APPROVED** [review]

**Pull request merged**
