### PR TITLE
mark fields `late final`

### PR DESCRIPTION
**Pull request by pq**
Learning as I go...  We can combine `late` and `final`!

https://dart.dev/null-safety/understanding-null-safety#late-final-variables

🤯 

/cc @devoncarew

### CODE REVIEW

**Review by devoncarew — APPROVED** [review]
Thanks! Yeah, that better expresses what these fields are doing.

**Comment by devoncarew** [comment]
Looks like some test failures though?

**Comment by pq** [comment]
Whoops.  A bug...  Looking.

**Comment by pq** [comment]
Yep.  Too zealous.

**Pull request merged**
