### PR TITLE
Updated example to be Dart 2 compliant, refactor CI tests, and other misc cleanup

### PR DESCRIPTION
**Pull request by chalin**
cc @kwalrath @kevmoo

### CODE REVIEW

**Comment by devoncarew** [comment]
Thanks for the PR! I have some feedback, am on mobile right now, and will review ~this evening.

**Comment by devoncarew** [comment]
@chalin, this PR mixes in a lot of separate concerns, including deleting IntelliJ metadata and changing the CI script, so I'll likely prepare a separate PR that just upgrades the pubspec version for Dart 2.

**Comment by chalin** [comment]
Thanks! Ok, with the max SDK set in #126, this has become a general cleanup PR. PTAL

**Comment by devoncarew** [comment]
OK, I have much of it recreated here: https://github.com/dart-lang/usage/pull/127

My reservations with this PR are the .travis.yaml and travis.sh changes, and deleting the IntelliJ metadata. If you revert those two sets of changes, I'm happy to land this PR intsead of the above.

**Comment by chalin** [comment]
> My reservations with this PR are the .travis.yaml and travis.sh changes, 

The same things are being tested as before, but the new Travis config splits things into jobs so that we can see each job in the Travis build summary. This seems to be standard practice for Dart packages. This way, if there is a failure in one of the jobs, it is easier to spot w/o having to read the entire Travis output.

> and deleting the IntelliJ metadata.

Two issues with the Idea metadata:

- It causes issues when the project is open in WebStorm: it complains about unrecognized project type.
- It is meant to be ignored according to the `.gitignore` (see below). If this project is meant to include such metadata, then the `.gitignore` file should be adjusted. https://github.com/dart-lang/usage/blob/0fc1761c32ce22c83886d799021a9f6182f9de91/.gitignore#L2

**Comment by devoncarew** [comment]
Re: the travis configs; many Dart projects do chose to use the updated rules - many don't. I prefer the simplicity and easy customizability of a shell script. It gives you slightly less out of the box, but it makes changing and customizing it very straightforward.

I don't care nearly as much about the IntelliJ metadata. When adding it to a project, you generally do ignore the .idea directory and still commit individual files in there. Some file define the project structure - which you want to share between users - and other define per-user config and settings, which you wouldn't want to commit.

**Comment by devoncarew** [comment]
@chalin, I think I'm going to land my other PR in preference to this one, but I do appreciate the contribution and the work here.

**Comment by chalin** [comment]
No problem. If there are any of the changes here that you'd still like after merging your PR, let me know.

**Pull request closed without merging**
