### PR TITLE
Kevmoo tweaks

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by devoncarew** [comment]
So much formatting!

One comment about the package version, then lgtm.

**Comment by kevmoo** [comment]
@devoncarew version?

**Comment by devoncarew** [comment]
Hmm, looks like my comment got lost; one sec.

**Comment by devoncarew** [comment]
I thought you'd bumped to `3.0.1-dev`; but the current version (`3.0.0-dev`) looks good.

**Pull request merged**
